name: Code activation
on:
  schedule:
    - cron: "0 0 1 * *" # Once a month
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '>=12.14.1'
    - name: Install dependencies
      run: npm ci
    - name: Install actions core
      run: npm i @actions/core 
    - name: Code activation
      run: node index.js
      env:
        HOYOLAB_COOKIES: ${{ secrets.HOYOLAB_COOKIES }}